version: '3'

volumes:
  nextcloud:
  db:
  redis:
  document_data:
  document_log:

services:
  db:
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=nextcloud
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis:/var/lib/redis
    command: "redis-server --requirepass ${REDIS_HOST_PASSWORD}"

  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    restart: always
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice

  app:
    container_name: nextcloud-app-server
    image: nextcloud:${NEXTCLOUD_VERSION}
    restart: always
    depends_on:
      - redis
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}
      - TRUSTED_PROXIES=171.18.0.0/16
      - POSTGRES_HOST=db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_HOST_PASSWORD=${REDIS_HOST_PASSWORD}
      # - OBJECTSTORE_S3_HOST=${OBJECTSTORE_S3_HOST}
      # - OBJECTSTORE_S3_BUCKET=${OBJECTSTORE_S3_BUCKET}
      # - OBJECTSTORE_S3_KEY=${OBJECTSTORE_S3_KEY}
      # - OBJECTSTORE_S3_SECRET=${OBJECTSTORE_S3_SECRET}
      # - OBJECTSTORE_S3_REGION=${OBJECTSTORE_S3_REGION}
      # - OBJECTSTORE_S3_SSL=${OBJECTSTORE_S3_SSL}
      # - OBJECTSTORE_S3_PORT=${OBJECTSTORE_S3_PORT}
      # - OBJECTSTORE_S3_USEPATH_STYLE=${OBJECTSTORE_S3_USEPATH_STYLE}

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - ${NEXTCLOUD_PORT}:80
    depends_on:
      - app
      - onlyoffice-document-server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
